### ISSUE TITLE
fysa: `placebo-npm`

### ISSUE THREAD

**Issue by blaggacao** [canva-public/js2nix#19]
https://github.com/svanderburg/placebo-npm had been brought to my attention and I don't want to hold private the knowledge of its existence.

It seems to be adding ecosystem capability in the same space than js2nix.

**Comment by olebedev** [comment]
> It seems to be adding ecosystem capability in the same space than js2nix.

Yeah, it seems kind of like that, but from my understanding it substitute NPM with Nix, try to mimic some behavior. I am not entirely sure here, the readme is a bit vague, unfortunately. The placebo term in the context of NPM is not entirely clear to me. 

Anyways, with `js2nix` it's possible to substitute some packages with dummy implementations if required for some of workflows, via overlays.

I heard about the author, he created `node2nix` and I am full of respect to that work, `node2nix` is definitely trying to do similar things on the field where `js2nix` operates.
